### ISSUE TITLE
g:ConqueTerm_SessionSupport needs check in autoload/conque.vim

### ISSUE THREAD

**Issue by scratch-nk** [wkentaro/conque.vim#2]
Hi,
g:ConqueTerm_SessionSupport is not defined -- in any case, best to make the check in autoload/conque_term.vim?

 Attaching patch:

[conque.vim.patch.txt](https://github.com/wkentaro/conque.vim/files/673991/conque.vim.patch.txt)

**Comment by wkentaro** [comment]
That sounds reasonable. Could you please send PR for this?

**Comment by wkentaro** [comment]
Fixed via #3 #4
